spring:
  application:
    name: cointransfer

  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password:
    url: 'jdbc:h2:mem:my_app'
  h2:
    console:
      enabled: true
      path: '/h2'
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

external:
  coindesk:
    url: https://kengp3.github.io/blog/coindesk.json